AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppSyncApiName:
    Type: String
    Description: IKNCU AppSync API
    Default: AppSyncSimpleTransform
  DynamoDBModelTableReadIOPS:
    Type: Number
    Description: The number of read IOPS the table should support.
    Default: 1
  DynamoDBModelTableWriteIOPS:
    Type: Number
    Description: The number of write IOPS the table should support.
    Default: 1
  AuthCognitoUserPoolId:
    Type: String
    Description: >-
      The id of an existing User Pool to connect. If this is changed, a user
      pool will not be created for you.
    Default: NONE
  AuthCognitoUserPoolName:
    Type: String
    Description: The name of the user pool.
    Default: AppSyncUserPool
  AuthCognitoUserPoolMobileClientName:
    Type: String
    Description: The name of the native user pool client.
    Default: CognitoNativeClient
  AuthCognitoUserPoolJSClientName:
    Type: String
    Description: The name of the web user pool client.
    Default: CognitoJSClient
  AuthCognitoUserPoolRefreshTokenValidity:
    Type: Number
    Description: 'The time limit, in days, after which the refresh token is no longer valid.'
    Default: 30
  ResolverBucket:
    Type: String
    Description: The name of the bucket containing the resolver templates
  AccountId:
    Type: String
    Description: AWS Account ID
  ResolverRootKey:
    Type: String
    Description: >-
      The s3 key of the folder containing the resolver templates in format
      {Type}.{Field}.[response|request].{Timestamp}
  DeploymentTimestamp:
    Type: String
    Description: >-
      The timestamp used to identify thie most recent version of the resolver
      templates in s3.
  schemaGraphql:
    Type: String
    Description: 'The S3 location for the Schema: schema.graphql'

Resources:
  GraphQLSchema:
    Type: 'AWS::AppSync::GraphQLSchema'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DefinitionS3Location: !Ref schemaGraphql
  GraphQLAPI:
    Type: 'AWS::AppSync::GraphQLApi'
    Properties:
      Name: !Ref AppSyncApiName
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !If
          - AuthShouldCreateUserPool
          - !Ref AuthCognitoUserPool
          - !Ref AuthCognitoUserPoolId
        AwsRegion: !Ref 'AWS::Region'
        DefaultAction: ALLOW
  GraphQLAPIKey:
    Type: 'AWS::AppSync::ApiKey'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId

  TableIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: Table-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:BatchWriteItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:Query'
                  - 'dynamodb:UpdateItem'
                Resource: !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref "AWS::Region"
                    - !Ref "AccountId"
                    - 'table/*'


  # TABLES

  TierTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Tier
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBModelTableReadIOPS
        WriteCapacityUnits: !Ref DynamoDBModelTableWriteIOPS

  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: User
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: tierId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: tierId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBModelTableReadIOPS
        WriteCapacityUnits: !Ref DynamoDBModelTableWriteIOPS

  # DATA SOURCES
  TierDataSource:
    Type: 'AWS::AppSync::DataSource'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      Name: TierTable
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt
        - TableIAMRole
        - Arn
      DynamoDBConfig:
        AwsRegion: !Select
          - 3
          - !Split
            - ':'
            - !GetAtt
              - TierTable
              - Arn
        TableName: !Ref TierTable
    DependsOn: TableIAMRole

  UserDataSource:
    Type: 'AWS::AppSync::DataSource'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      Name: UserTable
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt
        - TableIAMRole
        - Arn
      DynamoDBConfig:
        AwsRegion: !Select
          - 3
          - !Split
            - ':'
            - !GetAtt
              - UserTable
              - Arn
        TableName: !Ref UserTable
    DependsOn: TableIAMRole

  # RESOLVERS

  GetTierResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - TierDataSource
        - Name
      FieldName: getTier
      TypeName: Query
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - getTier
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - getTier
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema

  ListTierResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - TierDataSource
        - Name
      FieldName: listTiers
      TypeName: Query
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - listTiers
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - listTiers
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema

  CreateTierResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - TierDataSource
        - Name
      FieldName: createTier
      TypeName: Mutation
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - createTier
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - createTier
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema

  UpdateTierResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - TierDataSource
        - Name
      FieldName: updateTier
      TypeName: Mutation
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - updateTier
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - updateTier
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema

  DeleteTierResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - TierDataSource
        - Name
      FieldName: deleteTier
      TypeName: Mutation
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - deleteTier
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - deleteTier
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema

  GetUserResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - UserDataSource
        - Name
      FieldName: getUser
      TypeName: Query
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - getUser
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - getUser
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema
  ListUserResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - UserDataSource
        - Name
      FieldName: listUsers
      TypeName: Query
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - listUsers
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Query
                  - listUsers
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema
  CreateUserResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - UserDataSource
        - Name
      FieldName: createUser
      TypeName: Mutation
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - createUser
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - createUser
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema
  UpdateUserResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - UserDataSource
        - Name
      FieldName: updateUser
      TypeName: Mutation
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - updateUser
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - updateUser
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema
  DeleteUserResolver:
    Type: 'AWS::AppSync::Resolver'
    Properties:
      ApiId: !GetAtt
        - GraphQLAPI
        - ApiId
      DataSourceName: !GetAtt
        - UserDataSource
        - Name
      FieldName: deleteUser
      TypeName: Mutation
      RequestMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - deleteUser
                  - request
                  - !Ref DeploymentTimestamp
      ResponseMappingTemplateS3Location: !Join
        - ''
        - - 's3://'
          - !Join
            - /
            - - !Ref ResolverBucket
              - !Ref ResolverRootKey
              - !Join
                - .
                - - Mutation
                  - deleteUser
                  - response
                  - !Ref DeploymentTimestamp
    DependsOn: GraphQLSchema

  AuthCognitoUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: !Ref AuthCognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
      AutoVerifiedAttributes:
        - email
    Condition: AuthShouldCreateUserPool

  AuthCognitoUserPoolNativeClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: !Ref AuthCognitoUserPoolMobileClientName
      UserPoolId: !If
        - AuthShouldCreateUserPool
        - !Ref AuthCognitoUserPool
        - !Ref AuthCognitoUserPoolId
      GenerateSecret: true
      RefreshTokenValidity: !Ref AuthCognitoUserPoolRefreshTokenValidity
      ReadAttributes: []
      WriteAttributes: []
    Condition: AuthShouldCreateUserPool

  AuthCognitoUserPoolJSClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: !Ref AuthCognitoUserPoolJSClientName
      UserPoolId: !If
        - AuthShouldCreateUserPool
        - !Ref AuthCognitoUserPool
        - !Ref AuthCognitoUserPoolId
      GenerateSecret: false
      RefreshTokenValidity: !Ref AuthCognitoUserPoolRefreshTokenValidity
      ReadAttributes: []
      WriteAttributes: []
    Condition: AuthShouldCreateUserPool

Outputs:
  GraphQLAPIIdOutput:
    Description: Your GraphQL API ID.
    Value: !GetAtt
      - GraphQLAPI
      - ApiId
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - GraphQLApiId
  GraphQLAPIEndpointOutput:
    Description: Your GraphQL API endpoint.
    Value: !GetAtt
      - GraphQLAPI
      - GraphQLUrl
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - GraphQLApiEndpoint
  GraphQLAPIKeyOutput:
    Description: Your GraphQL API key. Provide via 'x-api-key' header.
    Value: !GetAtt
      - GraphQLAPIKey
      - ApiKey
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - GraphQLApiKey
  AuthCognitoUserPoolNativeClientId:
    Description: Amazon Cognito UserPools native client ID
    Value: !If
      - AuthShouldCreateUserPool
      - !Ref AuthCognitoUserPoolNativeClient
      - !Join
        - ' '
        - - 'See UserPool:'
          - !Ref AuthCognitoUserPoolId
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - CognitoNativeClient
  AuthCognitoUserPoolJSClientId:
    Description: Amazon Cognito UserPools JS client ID
    Value: !If
      - AuthShouldCreateUserPool
      - !Ref AuthCognitoUserPoolJSClient
      - !Join
        - ' '
        - - 'See UserPool:'
          - !Ref AuthCognitoUserPoolId
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - CognitoJSClient
  AuthCognitoUserPoolIdOutput:
    Description: Amazon Cognito UserPool id
    Value: !If
      - AuthShouldCreateUserPool
      - !Ref AuthCognitoUserPool
      - !Ref AuthCognitoUserPoolId
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - CognitoUserPoolId
Conditions:
  AuthShouldCreateUserPool: !Equals
    - !Ref AuthCognitoUserPoolId
    - NONE
