export interface ITimeZone {
  Id: string;
  UtcOffset: string;
  Name: string;
};

export const TimeZoneList = [
    { Id: 'Dateline Standard Time',           UtcOffset: '-12:00:00', Name: 'International Date Line West' },
    { Id: 'UTC-11',                           UtcOffset: '-11:00:00', Name: 'Coordinated Universal Time-11' },
    { Id: 'Aleutian Standard Time',           UtcOffset: '-10:00:00', Name: 'Aleutian Islands' },
    { Id: 'Hawaiian Standard Time',           UtcOffset: '-10:00:00', Name: 'Hawaii' },
    { Id: 'Marquesas Standard Time',          UtcOffset: '-09:30:00', Name: 'Marquesas Islands' },
    { Id: 'Alaskan Standard Time',            UtcOffset: '-09:00:00', Name: 'Alaska' },
    { Id: 'UTC-09',                           UtcOffset: '-09:00:00', Name: 'Coordinated Universal Time-09' },
    { Id: 'Pacific Standard Time (Mexico)',   UtcOffset: '-08:00:00', Name: 'Baja California' },
    { Id: 'UTC-08',                           UtcOffset: '-08:00:00', Name: 'Coordinated Universal Time-08' },
    { Id: 'Pacific Standard Time',            UtcOffset: '-08:00:00', Name: 'Pacific Time (US & Canada)' },
    { Id: 'US Mountain Standard Time',        UtcOffset: '-07:00:00', Name: 'Arizona' },
    { Id: 'Mountain Standard Time (Mexico)',  UtcOffset: '-07:00:00', Name: 'Chihuahua, La Paz, Mazatlan' },
    { Id: 'Mountain Standard Time',           UtcOffset: '-07:00:00', Name: 'Mountain Time (US & Canada)' },
    { Id: 'Central America Standard Time',    UtcOffset: '-06:00:00', Name: 'Central America' },
    { Id: 'Central Standard Time',            UtcOffset: '-06:00:00', Name: 'Central Time (US & Canada)' },
    { Id: 'Easter Island Standard Time',      UtcOffset: '-06:00:00', Name: 'Easter Island' },
    { Id: 'Central Standard Time (Mexico)',   UtcOffset: '-06:00:00', Name: 'Guadalajara, Mexico City, Monterrey' },
    { Id: 'Canada Central Standard Time',     UtcOffset: '-06:00:00', Name: 'Saskatchewan' },
    { Id: 'SA Pacific Standard Time',         UtcOffset: '-05:00:00', Name: 'Bogota, Lima, Quito, Rio Branco' },
    { Id: 'Eastern Standard Time (Mexico)',   UtcOffset: '-05:00:00', Name: 'Chetumal' },
    { Id: 'Eastern Standard Time',            UtcOffset: '-05:00:00', Name: 'Eastern Time (US & Canada)' },
    { Id: 'Haiti Standard Time',              UtcOffset: '-05:00:00', Name: 'Haiti' },
    { Id: 'Cuba Standard Time',               UtcOffset: '-05:00:00', Name: 'Havana' },
    { Id: 'US Eastern Standard Time',         UtcOffset: '-05:00:00', Name: 'Indiana (East)' },
    { Id: 'Turks And Caicos Standard Time',   UtcOffset: '-05:00:00', Name: 'Turks and Caicos' },
    { Id: 'Paraguay Standard Time',           UtcOffset: '-04:00:00', Name: 'Asuncion' },
    { Id: 'Atlantic Standard Time',           UtcOffset: '-04:00:00', Name: 'Atlantic Time (Canada)' },
    { Id: 'Venezuela Standard Time',          UtcOffset: '-04:00:00', Name: 'Caracas' },
    { Id: 'Central Brazilian Standard Time',  UtcOffset: '-04:00:00', Name: 'Cuiaba' },
    { Id: 'SA Western Standard Time',         UtcOffset: '-04:00:00', Name: 'Georgetown, La Paz, Manaus, San Juan' },
    { Id: 'Pacific SA Standard Time',         UtcOffset: '-04:00:00', Name: 'Santiago' },
    { Id: 'Newfoundland Standard Time',       UtcOffset: '-03:30:00', Name: 'Newfoundland' },
    { Id: 'Tocantins Standard Time',          UtcOffset: '-03:00:00', Name: 'Araguaina' },
    { Id: 'E. South America Standard Time',   UtcOffset: '-03:00:00', Name: 'Brasilia' },
    { Id: 'SA Eastern Standard Time',         UtcOffset: '-03:00:00', Name: 'Cayenne, Fortaleza' },
    { Id: 'Argentina Standard Time',          UtcOffset: '-03:00:00', Name: 'City of Buenos Aires' },
    { Id: 'Greenland Standard Time',          UtcOffset: '-03:00:00', Name: 'Greenland' },
    { Id: 'Montevideo Standard Time',         UtcOffset: '-03:00:00', Name: 'Montevideo' },
    { Id: 'Magallanes Standard Time',         UtcOffset: '-03:00:00', Name: 'Punta Arenas' },
    { Id: 'Saint Pierre Standard Time',       UtcOffset: '-03:00:00', Name: 'Saint Pierre and Miquelon' },
    { Id: 'Bahia Standard Time',              UtcOffset: '-03:00:00', Name: 'Salvador' },
    { Id: 'UTC-02',                           UtcOffset: '-02:00:00', Name: 'Coordinated Universal Time-02' },
    { Id: 'Mid-Atlantic Standard Time',       UtcOffset: '-02:00:00', Name: 'Mid-Atlantic - Old' },
    { Id: 'Azores Standard Time',             UtcOffset: '-01:00:00', Name: 'Azores' },
    { Id: 'Cape Verde Standard Time',         UtcOffset: '-01:00:00', Name: 'Cabo Verde Is.' },
    { Id: 'UTC',                              UtcOffset: '+00:00:00', Name: 'nated Universal Time' },
    { Id: 'GMT Standard Time',                UtcOffset: '+00:00:00', Name: 'Dublin, Edinburgh, Lisbon, London' },
    { Id: 'Greenwich Standard Time',          UtcOffset: '+00:00:00', Name: 'Monrovia, Reykjavik' },
    { Id: 'Sao Tome Standard Time',           UtcOffset: '+00:00:00', Name: 'Sao Tome' },
    { Id: 'W. Europe Standard Time',          UtcOffset: '+01:00:00', Name: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna' },
    { Id: 'Central Europe Standard Time',     UtcOffset: '+01:00:00', Name: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague' },
    { Id: 'Romance Standard Time',            UtcOffset: '+01:00:00', Name: 'Brussels, Copenhagen, Madrid, Paris' },
    { Id: 'Morocco Standard Time',            UtcOffset: '+01:00:00', Name: 'Casablanca' },
    { Id: 'Central European Standard Time',   UtcOffset: '+01:00:00', Name: 'Sarajevo, Skopje, Warsaw, Zagreb' },
    { Id: 'W. Central Africa Standard Time',  UtcOffset: '+01:00:00', Name: 'West Central Africa' },
    { Id: 'Jordan Standard Time',             UtcOffset: '+02:00:00', Name: 'Amman' },
    { Id: 'GTB Standard Time',                UtcOffset: '+02:00:00', Name: 'Athens, Bucharest' },
    { Id: 'Middle East Standard Time',        UtcOffset: '+02:00:00', Name: 'Beirut' },
    { Id: 'Egypt Standard Time',              UtcOffset: '+02:00:00', Name: 'Cairo' },
    { Id: 'E. Europe Standard Time',          UtcOffset: '+02:00:00', Name: 'Chisinau' },
    { Id: 'Syria Standard Time',              UtcOffset: '+02:00:00', Name: 'Damascus' },
    { Id: 'West Bank Standard Time',          UtcOffset: '+02:00:00', Name: 'Gaza, Hebron' },
    { Id: 'South Africa Standard Time',       UtcOffset: '+02:00:00', Name: 'Harare, Pretoria' },
    { Id: 'FLE Standard Time',                UtcOffset: '+02:00:00', Name: 'Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius' },
    { Id: 'Israel Standard Time',             UtcOffset: '+02:00:00', Name: 'Jerusalem' },
    { Id: 'Kaliningrad Standard Time',        UtcOffset: '+02:00:00', Name: 'Kaliningrad' },
    { Id: 'Sudan Standard Time',              UtcOffset: '+02:00:00', Name: 'Khartoum' },
    { Id: 'Libya Standard Time',              UtcOffset: '+02:00:00', Name: 'Tripoli' },
    { Id: 'Namibia Standard Time',            UtcOffset: '+02:00:00', Name: 'Windhoek' },
    { Id: 'Arabic Standard Time',             UtcOffset: '+03:00:00', Name: 'Baghdad' },
    { Id: 'Turkey Standard Time',             UtcOffset: '+03:00:00', Name: 'Istanbul' },
    { Id: 'Arab Standard Time',               UtcOffset: '+03:00:00', Name: 'Kuwait, Riyadh' },
    { Id: 'Belarus Standard Time',            UtcOffset: '+03:00:00', Name: 'Minsk' },
    { Id: 'Russian Standard Time',            UtcOffset: '+03:00:00', Name: 'Moscow, St. Petersburg' },
    { Id: 'E. Africa Standard Time',          UtcOffset: '+03:00:00', Name: 'Nairobi' },
    { Id: 'Iran Standard Time',               UtcOffset: '+03:30:00', Name: 'Tehran' },
    { Id: 'Arabian Standard Time',            UtcOffset: '+04:00:00', Name: 'Abu Dhabi, Muscat' },
    { Id: 'Astrakhan Standard Time',          UtcOffset: '+04:00:00', Name: 'Astrakhan, Ulyanovsk' },
    { Id: 'Azerbaijan Standard Time',         UtcOffset: '+04:00:00', Name: 'Baku' },
    { Id: 'Russia Time Zone 3',               UtcOffset: '+04:00:00', Name: 'Izhevsk, Samara' },
    { Id: 'Mauritius Standard Time',          UtcOffset: '+04:00:00', Name: 'Port Louis' },
    { Id: 'Saratov Standard Time',            UtcOffset: '+04:00:00', Name: 'Saratov' },
    { Id: 'Georgian Standard Time',           UtcOffset: '+04:00:00', Name: 'Tbilisi' },
    { Id: 'Volgograd Standard Time',          UtcOffset: '+04:00:00', Name: 'Volgograd' },
    { Id: 'Caucasus Standard Time',           UtcOffset: '+04:00:00', Name: 'Yerevan' },
    { Id: 'Afghanistan Standard Time',        UtcOffset: '+04:30:00', Name: 'Kabul' },
    { Id: 'West Asia Standard Time',          UtcOffset: '+05:00:00', Name: 'Ashgabat, Tashkent' },
    { Id: 'Ekaterinburg Standard Time',       UtcOffset: '+05:00:00', Name: 'Ekaterinburg' },
    { Id: 'Pakistan Standard Time',           UtcOffset: '+05:00:00', Name: 'Islamabad, Karachi' },
    { Id: 'Qyzylorda Standard Time',          UtcOffset: '+05:00:00', Name: 'Qyzylorda' },
    { Id: 'India Standard Time',              UtcOffset: '+05:30:00', Name: 'Chennai, Kolkata, Mumbai, New Delhi' },
    { Id: 'Sri Lanka Standard Time',          UtcOffset: '+05:30:00', Name: 'Sri Jayawardenepura' },
    { Id: 'Nepal Standard Time',              UtcOffset: '+05:45:00', Name: 'Kathmandu' },
    { Id: 'Central Asia Standard Time',       UtcOffset: '+06:00:00', Name: 'Astana' },
    { Id: 'Bangladesh Standard Time',         UtcOffset: '+06:00:00', Name: 'Dhaka' },
    { Id: 'Omsk Standard Time',               UtcOffset: '+06:00:00', Name: 'Omsk' },
    { Id: 'Myanmar Standard Time',            UtcOffset: '+06:30:00', Name: 'Yangon (Rangoon)' },
    { Id: 'SE Asia Standard Time',            UtcOffset: '+07:00:00', Name: 'Bangkok, Hanoi, Jakarta' },
    { Id: 'Altai Standard Time',              UtcOffset: '+07:00:00', Name: 'Barnaul, Gorno-Altaysk' },
    { Id: 'W. Mongolia Standard Time',        UtcOffset: '+07:00:00', Name: 'Hovd' },
    { Id: 'North Asia Standard Time',         UtcOffset: '+07:00:00', Name: 'Krasnoyarsk' },
    { Id: 'N. Central Asia Standard Time',    UtcOffset: '+07:00:00', Name: 'Novosibirsk' },
    { Id: 'Tomsk Standard Time',              UtcOffset: '+07:00:00', Name: 'Tomsk' },
    { Id: 'China Standard Time',              UtcOffset: '+08:00:00', Name: 'Beijing, Chongqing, Hong Kong, Urumqi' },
    { Id: 'North Asia East Standard Time',    UtcOffset: '+08:00:00', Name: 'Irkutsk' },
    { Id: 'Singapore Standard Time',          UtcOffset: '+08:00:00', Name: 'Kuala Lumpur, Singapore' },
    { Id: 'W. Australia Standard Time',       UtcOffset: '+08:00:00', Name: 'Perth' },
    { Id: 'Taipei Standard Time',             UtcOffset: '+08:00:00', Name: 'Taipei' },
    { Id: 'Ulaanbaatar Standard Time',        UtcOffset: '+08:00:00', Name: 'Ulaanbaatar' },
    { Id: 'Aus Central W. Standard Time',     UtcOffset: '+08:45:00', Name: 'Eucla' },
    { Id: 'Transbaikal Standard Time',        UtcOffset: '+09:00:00', Name: 'Chita' },
    { Id: 'Tokyo Standard Time',              UtcOffset: '+09:00:00', Name: 'Osaka, Sapporo, Tokyo' },
    { Id: 'North Korea Standard Time',        UtcOffset: '+09:00:00', Name: 'Pyongyang' },
    { Id: 'Korea Standard Time',              UtcOffset: '+09:00:00', Name: 'Seoul' },
    { Id: 'Yakutsk Standard Time',            UtcOffset: '+09:00:00', Name: 'Yakutsk' },
    { Id: 'Cen. Australia Standard Time',     UtcOffset: '+09:30:00', Name: 'Adelaide' },
    { Id: 'AUS Central Standard Time',        UtcOffset: '+09:30:00', Name: 'Darwin' },
    { Id: 'E. Australia Standard Time',       UtcOffset: '+10:00:00', Name: 'Brisbane' },
    { Id: 'AUS Eastern Standard Time',        UtcOffset: '+10:00:00', Name: 'Canberra, Melbourne, Sydney' },
    { Id: 'West Pacific Standard Time',       UtcOffset: '+10:00:00', Name: 'Guam, Port Moresby' },
    { Id: 'Tasmania Standard Time',           UtcOffset: '+10:00:00', Name: 'Hobart' },
    { Id: 'Vladivostok Standard Time',        UtcOffset: '+10:00:00', Name: 'Vladivostok' },
    { Id: 'Lord Howe Standard Time',          UtcOffset: '+10:30:00', Name: 'Lord Howe Island' },
    { Id: 'Bougainville Standard Time',       UtcOffset: '+11:00:00', Name: 'Bougainville Island' },
    { Id: 'Russia Time Zone 10',              UtcOffset: '+11:00:00', Name: 'Chokurdakh' },
    { Id: 'Magadan Standard Time',            UtcOffset: '+11:00:00', Name: 'Magadan' },
    { Id: 'Norfolk Standard Time',            UtcOffset: '+11:00:00', Name: 'Norfolk Island' },
    { Id: 'Sakhalin Standard Time',           UtcOffset: '+11:00:00', Name: 'Sakhalin' },
    { Id: 'Central Pacific Standard Time',    UtcOffset: '+11:00:00', Name: 'Solomon Is., New Caledonia' },
    { Id: 'Russia Time Zone 11',              UtcOffset: '+12:00:00', Name: 'Anadyr, Petropavlovsk-Kamchatsky' },
    { Id: 'New Zealand Standard Time',        UtcOffset: '+12:00:00', Name: 'Auckland, Wellington' },
    { Id: 'UTC+12',                           UtcOffset: '+12:00:00', Name: 'Coordinated Universal Time+12' },
    { Id: 'Fiji Standard Time',               UtcOffset: '+12:00:00', Name: 'Fiji' },
    { Id: 'Kamchatka Standard Time',          UtcOffset: '+12:00:00', Name: 'Petropavlovsk-Kamchatsky - Old' },
    { Id: 'Chatham Islands Standard Time',    UtcOffset: '+12:45:00', Name: 'Chatham Islands' },
    { Id: 'UTC+13',                           UtcOffset: '+13:00:00', Name: 'Coordinated Universal Time+13' },
    { Id: 'Tonga Standard Time',              UtcOffset: '+13:00:00', Name: 'Nuku\'alofa' },
    { Id: 'Samoa Standard Time',              UtcOffset: '+13:00:00', Name: 'Samoa' },
    { Id: 'Line Islands Standard Time',       UtcOffset: '+14:00:00', Name: 'Kiritimati Island' }
] as ITimeZone[];


// const TimeZoneList = [
//   { GmtOffset: '-11:00', Code: 'Pacific/Niue',                     Name: 'Niue' },
//   { GmtOffset: '-11:00', Code: 'Pacific/Pago_Pago',                Name: 'Pago Pago' },
//   { GmtOffset: '-10:00', Code: 'Pacific/Honolulu',                 Name: 'Hawaii Time' },
//   { GmtOffset: '-10:00', Code: 'Pacific/Rarotonga',                Name: 'Rarotonga' },
//   { GmtOffset: '-10:00', Code: 'Pacific/Tahiti',                   Name: 'Tahiti' },
//   { GmtOffset: '-09:30', Code: 'Pacific/Marquesas',                Name: 'Marquesas' },,
//   { GmtOffset: '-09:00', Code: 'America/Anchorage',                Name: 'Alaska Time' },
//   { GmtOffset: '-09:00', Code: 'Pacific/Gambier',                  Name: 'Gambier' },
//   { GmtOffset: '-08:00', Code: 'America/Los_Angeles',              Name: 'Pacific Time' },
//   { GmtOffset: '-08:00', Code: 'America/Tijuana',                  Name: 'Pacific Time - Tijuana' },
//   { GmtOffset: '-08:00', Code: 'America/Vancouver',                Name: 'Pacific Time - Vancouver' },
//   { GmtOffset: '-08:00', Code: 'America/Whitehorse',               Name: 'Pacific Time - Whitehorse' },
//   { GmtOffset: '-08:00', Code: 'Pacific/Pitcairn',                 Name: 'Pitcairn' },
//   { GmtOffset: '-07:00', Code: 'America/Dawson_Creek',             Name: 'Mountain Time - Dawson Creek' },
//   { GmtOffset: '-07:00', Code: 'America/Denver',                   Name: 'Mountain Time' },
//   { GmtOffset: '-07:00', Code: 'America/Edmonton',                 Name: 'Mountain Time - Edmonton' },
//   { GmtOffset: '-07:00', Code: 'America/Hermosillo',               Name: 'Mountain Time - Hermosillo' },
//   { GmtOffset: '-07:00', Code: 'America/Mazatlan',                 Name: 'Mountain Time - Chihuahua, Mazatlan' },
//   { GmtOffset: '-07:00', Code: 'America/Phoenix',                  Name: 'Mountain Time - Arizona' },
//   { GmtOffset: '-07:00', Code: 'America/Yellowknife',              Name: 'Mountain Time - Yellowknife' },
//   { GmtOffset: '-06:00', Code: 'America/Belize',                   Name: 'Belize' },
//   { GmtOffset: '-06:00', Code: 'America/Chicago',                  Name: 'Central Time' },
//   { GmtOffset: '-06:00', Code: 'America/Costa_Rica',               Name: 'Costa Rica' },
//   { GmtOffset: '-06:00', Code: 'America/El_Salvador',              Name: 'El Salvador' },
//   { GmtOffset: '-06:00', Code: 'America/Guatemala',                Name: 'Guatemala' },
//   { GmtOffset: '-06:00', Code: 'America/Managua',                  Name: 'Managua' },
//   { GmtOffset: '-06:00', Code: 'America/Mexico_City',              Name: 'Central Time - Mexico City' },
//   { GmtOffset: '-06:00', Code: 'America/Regina',                   Name: 'Central Time - Regina' },
//   { GmtOffset: '-06:00', Code: 'America/Tegucigalpa',              Name: 'Central Time - Tegucigalpa' },
//   { GmtOffset: '-06:00', Code: 'America/Winnipeg',                 Name: 'Central Time - Winnipeg' },
//   { GmtOffset: '-06:00', Code: 'Pacific/Galapagos',                Name: 'Galapagos' },
//   { GmtOffset: '-05:00', Code: 'America/Bogota',                   Name: 'Bogota' },
//   { GmtOffset: '-05:00', Code: 'America/Cancun',                   Name: 'America Cancun' },
//   { GmtOffset: '-05:00', Code: 'America/Cayman',                   Name: 'Cayman' },
//   { GmtOffset: '-05:00', Code: 'America/Guayaquil',                Name: 'Guayaquil' },
//   { GmtOffset: '-05:00', Code: 'America/Havana',                   Name: 'Havana' },
//   { GmtOffset: '-05:00', Code: 'America/Iqaluit',                  Name: 'Eastern Time - Iqaluit' },
//   { GmtOffset: '-05:00', Code: 'America/Jamaica',                  Name: 'Jamaica' },
//   { GmtOffset: '-05:00', Code: 'America/Lima',                     Name: 'Lima' },
//   { GmtOffset: '-05:00', Code: 'America/Nassau',                   Name: 'Nassau' },
//   { GmtOffset: '-05:00', Code: 'America/New_York',                 Name: 'Eastern Time' },
//   { GmtOffset: '-05:00', Code: 'America/Panama',                   Name: 'Panama' },
//   { GmtOffset: '-05:00', Code: 'America/Port-au-Prince',           Name: 'Port-au-Prince' },
//   { GmtOffset: '-05:00', Code: 'America/Rio_Branco',               Name: 'Rio Branco' },
//   { GmtOffset: '-05:00', Code: 'America/Toronto',                  Name: 'Eastern Time - Toronto' },
//   { GmtOffset: '-05:00', Code: 'Pacific/Easter',                   Name: 'Easter Island' },
//   { GmtOffset: '-04:30', Code: 'America/Caracas',                  Name: 'Caracas' },
//   { GmtOffset: '-03:00', Code: 'America/Asuncion',                 Name: 'Asuncion' },
//   { GmtOffset: '-04:00', Code: 'America/Barbados',                 Name: 'Barbados' },
//   { GmtOffset: '-04:00', Code: 'America/Boa_Vista',                Name: 'Boa Vista' },
//   { GmtOffset: '-03:00', Code: 'America/Campo_Grande',             Name: 'Campo Grande' },
//   { GmtOffset: '-03:00', Code: 'America/Cuiaba',                   Name: 'Cuiaba' },
//   { GmtOffset: '-04:00', Code: 'America/Curacao',                  Name: 'Curacao' },
//   { GmtOffset: '-04:00', Code: 'America/Grand_Turk',               Name: 'Grand Turk' },
//   { GmtOffset: '-04:00', Code: 'America/Guyana',                   Name: 'Guyana' },
//   { GmtOffset: '-04:00', Code: 'America/Halifax',                  Name: 'Atlantic Time - Halifax' },
//   { GmtOffset: '-04:00', Code: 'America/La_Paz',                   Name: 'La Paz' },
//   { GmtOffset: '-04:00', Code: 'America/Manaus',                   Name: 'Manaus' },
//   { GmtOffset: '-04:00', Code: 'America/Martinique',               Name: 'Martinique' },
//   { GmtOffset: '-04:00', Code: 'America/Port_of_Spain',            Name: 'Port of Spain' },
//   { GmtOffset: '-04:00', Code: 'America/Porto_Velho',              Name: 'Porto Velho' },
//   { GmtOffset: '-04:00', Code: 'America/Puerto_Rico',              Name: 'Puerto Rico' },
//   { GmtOffset: '-04:00', Code: 'America/Santo_Domingo',            Name: 'Santo Domingo' },
//   { GmtOffset: '-04:00', Code: 'America/Thule',                    Name: 'Thule' },
//   { GmtOffset: '-04:00', Code: 'Atlantic/Bermuda',                 Name: 'Bermuda' },
//   { GmtOffset: '-03:30', Code: 'America/St_Johns',                 Name: 'Newfoundland Time - St. Johns' },
//   { GmtOffset: '-03:00', Code: 'America/Araguaina',                Name: 'Araguaina' },
//   { GmtOffset: '-03:00', Code: 'America/Argentina/Buenos_Aires',   Name: 'Buenos Aires' },
//   { GmtOffset: '-03:00', Code: 'America/Bahia',                    Name: 'Salvador' },
//   { GmtOffset: '-03:00', Code: 'America/Belem',                    Name: 'Belem' },
//   { GmtOffset: '-03:00', Code: 'America/Cayenne',                  Name: 'Cayenne' },
//   { GmtOffset: '-03:00', Code: 'America/Fortaleza',                Name: 'Fortaleza' },
//   { GmtOffset: '-03:00', Code: 'America/Godthab',                  Name: 'Godthab' },
//   { GmtOffset: '-03:00', Code: 'America/Maceio',                   Name: 'Maceio' },
//   { GmtOffset: '-03:00', Code: 'America/Miquelon',                 Name: 'Miquelon' },
//   { GmtOffset: '-03:00', Code: 'America/Montevideo',               Name: 'Montevideo' },
//   { GmtOffset: '-03:00', Code: 'America/Paramaribo',               Name: 'Paramaribo' },
//   { GmtOffset: '-03:00', Code: 'America/Recife',                   Name: 'Recife' },
//   { GmtOffset: '-03:00', Code: 'America/Santiago',                 Name: 'Santiago' },
//   { GmtOffset: '-02:00', Code: 'America/Sao_Paulo',                Name: 'Sao Paulo' },
//   { GmtOffset: '-03:00', Code: 'Antarctica/Palmer',                Name: 'Palmer' },
//   { GmtOffset: '-03:00', Code: 'Antarctica/Rothera',               Name: 'Rothera' },
//   { GmtOffset: '-03:00', Code: 'Atlantic/Stanley',                 Name: 'Stanley' },
//   { GmtOffset: '-02:00', Code: 'America/Noronha',                  Name: 'Noronha' },
//   { GmtOffset: '-02:00', Code: 'Atlantic/South_Georgia',           Name: 'South Georgia' },
//   { GmtOffset: '-01:00', Code: 'America/Scoresbysund',             Name: 'Scoresbysund' },
//   { GmtOffset: '-01:00', Code: 'Atlantic/Azores',                  Name: 'Azores' },
//   { GmtOffset: '-01:00', Code: 'Atlantic/Cape_Verde',              Name: 'Cape Verde' },
//   { GmtOffset: '+00:00', Code: 'Africa/Abidjan',                   Name: 'Abidjan' },
//   { GmtOffset: '+00:00', Code: 'Africa/Accra',                     Name: 'Accra' },
//   { GmtOffset: '+00:00', Code: 'Africa/Bissau',                    Name: 'Bissau' },
//   { GmtOffset: '+00:00', Code: 'Africa/Casablanca',                Name: 'Casablanca' },
//   { GmtOffset: '+00:00', Code: 'Africa/El_Aaiun',                  Name: 'El Aaiun' },
//   { GmtOffset: '+00:00', Code: 'Africa/Monrovia',                  Name: 'Monrovia' },
//   { GmtOffset: '+00:00', Code: 'America/Danmarkshavn',             Name: 'Danmarkshavn' },
//   { GmtOffset: '+00:00', Code: 'Atlantic/Canary',                  Name: 'Canary Islands' },
//   { GmtOffset: '+00:00', Code: 'Atlantic/Faroe',                   Name: 'Faeroe' },
//   { GmtOffset: '+00:00', Code: 'Atlantic/Reykjavik',               Name: 'Reykjavik' },
//   { GmtOffset: '+00:00', Code: 'Etc/GMT',                          Name: 'GMT (no daylight saving)' },
//   { GmtOffset: '+00:00', Code: 'Europe/Dublin',                    Name: 'Dublin' },
//   { GmtOffset: '+00:00', Code: 'Europe/Lisbon',                    Name: 'Lisbon' },
//   { GmtOffset: '+00:00', Code: 'Europe/London',                    Name: 'London' },
//   { GmtOffset: '+01:00', Code: 'Africa/Algiers',                   Name: 'Algiers' },
//   { GmtOffset: '+01:00', Code: 'Africa/Ceuta',                     Name: 'Ceuta' },
//   { GmtOffset: '+01:00', Code: 'Africa/Lagos',                     Name: 'Lagos' },
//   { GmtOffset: '+01:00', Code: 'Africa/Ndjamena',                  Name: 'Ndjamena' },
//   { GmtOffset: '+01:00', Code: 'Africa/Tunis',                     Name: 'Tunis' },
//   { GmtOffset: '+02:00', Code: 'Africa/Windhoek',                  Name: 'Windhoek' },
//   { GmtOffset: '+01:00', Code: 'Europe/Amsterdam',                 Name: 'Amsterdam' },
//   { GmtOffset: '+01:00', Code: 'Europe/Andorra',                   Name: 'Andorra' },
//   { GmtOffset: '+01:00', Code: 'Europe/Belgrade',                  Name: 'Central European Time - Belgrade' },
//   { GmtOffset: '+01:00', Code: 'Europe/Berlin',                    Name: 'Berlin' },
//   { GmtOffset: '+01:00', Code: 'Europe/Brussels',                  Name: 'Brussels' },
//   { GmtOffset: '+01:00', Code: 'Europe/Budapest',                  Name: 'Budapest' },
//   { GmtOffset: '+01:00', Code: 'Europe/Copenhagen',                Name: 'Copenhagen' },
//   { GmtOffset: '+01:00', Code: 'Europe/Gibraltar',                 Name: 'Gibraltar' },
//   { GmtOffset: '+01:00', Code: 'Europe/Luxembourg',                Name: 'Luxembourg' },
//   { GmtOffset: '+01:00', Code: 'Europe/Madrid',                    Name: 'Madrid' },
//   { GmtOffset: '+01:00', Code: 'Europe/Malta',                     Name: 'Malta' },
//   { GmtOffset: '+01:00', Code: 'Europe/Monaco',                    Name: 'Monaco' },
//   { GmtOffset: '+01:00', Code: 'Europe/Oslo',                      Name: 'Oslo' },
//   { GmtOffset: '+01:00', Code: 'Europe/Paris',                     Name: 'Paris' },
//   { GmtOffset: '+01:00', Code: 'Europe/Prague',                    Name: 'Central European Time - Prague' },
//   { GmtOffset: '+01:00', Code: 'Europe/Rome',                      Name: 'Rome' },
//   { GmtOffset: '+01:00', Code: 'Europe/Stockholm',                 Name: 'Stockholm' },
//   { GmtOffset: '+01:00', Code: 'Europe/Tirane',                    Name: 'Tirane' },
//   { GmtOffset: '+01:00', Code: 'Europe/Vienna',                    Name: 'Vienna' },
//   { GmtOffset: '+01:00', Code: 'Europe/Warsaw',                    Name: 'Warsaw' },
//   { GmtOffset: '+01:00', Code: 'Europe/Zurich',                    Name: 'Zurich' },
//   { GmtOffset: '+02:00', Code: 'Africa/Cairo',                     Name: 'Cairo' },
//   { GmtOffset: '+02:00', Code: 'Africa/Johannesburg',              Name: 'Johannesburg' },
//   { GmtOffset: '+02:00', Code: 'Africa/Maputo',                    Name: 'Maputo' },
//   { GmtOffset: '+02:00', Code: 'Africa/Tripoli',                   Name: 'Tripoli' },
//   { GmtOffset: '+02:00', Code: 'Asia/Amman',                       Name: 'Amman' },
//   { GmtOffset: '+02:00', Code: 'Asia/Beirut',                      Name: 'Beirut' },
//   { GmtOffset: '+02:00', Code: 'Asia/Damascus',                    Name: 'Damascus' },
//   { GmtOffset: '+02:00', Code: 'Asia/Gaza',                        Name: 'Gaza' },
//   { GmtOffset: '+02:00', Code: 'Asia/Jerusalem',                   Name: 'Jerusalem' },
//   { GmtOffset: '+02:00', Code: 'Asia/Nicosia',                     Name: 'Nicosia' },
//   { GmtOffset: '+02:00', Code: 'Europe/Athens',                    Name: 'Athens' },
//   { GmtOffset: '+02:00', Code: 'Europe/Bucharest',                 Name: 'Bucharest' },
//   { GmtOffset: '+02:00', Code: 'Europe/Chisinau',                  Name: 'Chisinau' },
//   { GmtOffset: '+02:00', Code: 'Europe/Helsinki',                  Name: 'Helsinki' },
//   { GmtOffset: '+02:00', Code: 'Europe/Istanbul',                  Name: 'Istanbul' },
//   { GmtOffset: '+02:00', Code: 'Europe/Kaliningrad',               Name: 'Moscow-01 - Kaliningrad' },
//   { GmtOffset: '+02:00', Code: 'Europe/Kiev',                      Name: 'Kiev' },
//   { GmtOffset: '+02:00', Code: 'Europe/Riga',                      Name: 'Riga' },
//   { GmtOffset: '+02:00', Code: 'Europe/Sofia',                     Name: 'Sofia' },
//   { GmtOffset: '+02:00', Code: 'Europe/Tallinn',                   Name: 'Tallinn' },
//   { GmtOffset: '+02:00', Code: 'Europe/Vilnius',                   Name: 'Vilnius' },
//   { GmtOffset: '+03:00', Code: 'Africa/Khartoum',                  Name: 'Khartoum' },
//   { GmtOffset: '+03:00', Code: 'Africa/Nairobi',                   Name: 'Nairobi' },
//   { GmtOffset: '+03:00', Code: 'Antarctica/Syowa',                 Name: 'Syowa' },
//   { GmtOffset: '+03:00', Code: 'Asia/Baghdad',                     Name: 'Baghdad' },
//   { GmtOffset: '+03:00', Code: 'Asia/Qatar',                       Name: 'Qatar' },
//   { GmtOffset: '+03:00', Code: 'Asia/Riyadh',                      Name: 'Riyadh' },
//   { GmtOffset: '+03:00', Code: 'Europe/Minsk',                     Name: 'Minsk' },
//   { GmtOffset: '+03:00', Code: 'Europe/Moscow',                    Name: 'Moscow - Moscow' },
//   { GmtOffset: '+03:30', Code: 'Asia/Tehran',                      Name: 'Tehran' },
//   { GmtOffset: '+04:00', Code: 'Asia/Baku',                        Name: 'Baku' },
//   { GmtOffset: '+04:00', Code: 'Asia/Dubai',                       Name: 'Dubai' },
//   { GmtOffset: '+04:00', Code: 'Asia/Tbilisi',                     Name: 'Tbilisi' },
//   { GmtOffset: '+04:00', Code: 'Asia/Yerevan',                     Name: 'Yerevan' },
//   { GmtOffset: '+04:00', Code: 'Europe/Samara',                    Name: 'Moscow+01 - Samara' },
//   { GmtOffset: '+04:00', Code: 'Indian/Mahe',                      Name: 'Mahe' },
//   { GmtOffset: '+04:00', Code: 'Indian/Mauritius',                 Name: 'Mauritius' },
//   { GmtOffset: '+04:00', Code: 'Indian/Reunion',                   Name: 'Reunion' },
//   { GmtOffset: '+04:30', Code: 'Asia/Kabul',                       Name: 'Kabul' },
//   { GmtOffset: '+05:00', Code: 'Antarctica/Mawson',                Name: 'Mawson' },
//   { GmtOffset: '+05:00', Code: 'Asia/Aqtau',                       Name: 'Aqtau' },
//   { GmtOffset: '+05:00', Code: 'Asia/Aqtobe',                      Name: 'Aqtobe' },
//   { GmtOffset: '+05:00', Code: 'Asia/Ashgabat',                    Name: 'Ashgabat' },
//   { GmtOffset: '+05:00', Code: 'Asia/Dushanbe',                    Name: 'Dushanbe' },
//   { GmtOffset: '+05:00', Code: 'Asia/Karachi',                     Name: 'Karachi' },
//   { GmtOffset: '+05:00', Code: 'Asia/Tashkent',                    Name: 'Tashkent' },
//   { GmtOffset: '+05:00', Code: 'Asia/Yekaterinburg',               Name: 'Moscow+02 - Yekaterinburg' },
//   { GmtOffset: '+05:00', Code: 'Indian/Kerguelen',                 Name: 'Kerguelen' },
//   { GmtOffset: '+05:00', Code: 'Indian/Maldives',                  Name: 'Maldives' },
//   { GmtOffset: '+05:30', Code: 'Asia/Calcutta',                    Name: 'India Standard Time' },
//   { GmtOffset: '+05:30', Code: 'Asia/Colombo',                     Name: 'Colombo' },
//   { GmtOffset: '+05:45', Code: 'Asia/Katmandu',                    Name: 'Katmandu' },
//   { GmtOffset: '+06:00', Code: 'Antarctica/Vostok',                Name: 'Vostok' },
//   { GmtOffset: '+06:00', Code: 'Asia/Almaty',                      Name: 'Almaty' },
//   { GmtOffset: '+06:00', Code: 'Asia/Bishkek',                     Name: 'Bishkek' },
//   { GmtOffset: '+06:00', Code: 'Asia/Dhaka',                       Name: 'Dhaka' },
//   { GmtOffset: '+06:00', Code: 'Asia/Omsk',                        Name: 'Moscow+03 - Omsk, Novosibirsk' },
//   { GmtOffset: '+06:00', Code: 'Asia/Thimphu',                     Name: 'Thimphu' },
//   { GmtOffset: '+06:00', Code: 'Indian/Chagos',                    Name: 'Chagos' },
//   { GmtOffset: '+06:30', Code: 'Asia/Rangoon',                     Name: 'Rangoon' },
//   { GmtOffset: '+06:30', Code: 'Indian/Cocos',                     Name: 'Cocos' },
//   { GmtOffset: '+07:00', Code: 'Antarctica/Davis',                 Name: 'Davis' },
//   { GmtOffset: '+07:00', Code: 'Asia/Bangkok',                     Name: 'Bangkok' },
//   { GmtOffset: '+07:00', Code: 'Asia/Hovd',                        Name: 'Hovd' },
//   { GmtOffset: '+07:00', Code: 'Asia/Jakarta',                     Name: 'Jakarta' },
//   { GmtOffset: '+07:00', Code: 'Asia/Krasnoyarsk',                 Name: 'Moscow+04 - Krasnoyarsk' },
//   { GmtOffset: '+07:00', Code: 'Asia/Saigon',                      Name: 'Hanoi' },
//   { GmtOffset: '+07:00', Code: 'Asia/Ho_Chi_Minh',                 Name: 'Ho Chi Minh' },
//   { GmtOffset: '+07:00', Code: 'Indian/Christmas',                 Name: 'Christmas' },
//   { GmtOffset: '+08:00', Code: 'Antarctica/Casey',                 Name: 'Casey' },
//   { GmtOffset: '+08:00', Code: 'Asia/Brunei',                      Name: 'Brunei' },
//   { GmtOffset: '+08:00', Code: 'Asia/Choibalsan',                  Name: 'Choibalsan' },
//   { GmtOffset: '+08:00', Code: 'Asia/Hong_Kong',                   Name: 'Hong Kong' },
//   { GmtOffset: '+08:00', Code: 'Asia/Irkutsk',                     Name: 'Moscow+05 - Irkutsk' },
//   { GmtOffset: '+08:00', Code: 'Asia/Kuala_Lumpur',                Name: 'Kuala Lumpur' },
//   { GmtOffset: '+08:00', Code: 'Asia/Macau',                       Name: 'Macau' },
//   { GmtOffset: '+08:00', Code: 'Asia/Makassar',                    Name: 'Makassar' },
//   { GmtOffset: '+08:00', Code: 'Asia/Manila',                      Name: 'Manila' },
//   { GmtOffset: '+08:00', Code: 'Asia/Shanghai',                    Name: 'China Time - Beijing' },
//   { GmtOffset: '+08:00', Code: 'Asia/Singapore',                   Name: 'Singapore' },
//   { GmtOffset: '+08:00', Code: 'Asia/Taipei',                      Name: 'Taipei' },
//   { GmtOffset: '+08:00', Code: 'Asia/Ulaanbaatar',                 Name: 'Ulaanbaatar' },
//   { GmtOffset: '+08:00', Code: 'Australia/Perth',                  Name: 'Western Time - Perth' },
//   { GmtOffset: '+08:30', Code: 'Asia/Pyongyang',                   Name: 'Pyongyang' },
//   { GmtOffset: '+09:00', Code: 'Asia/Dili',                        Name: 'Dili' },
//   { GmtOffset: '+09:00', Code: 'Asia/Jayapura',                    Name: 'Jayapura' },
//   { GmtOffset: '+09:00', Code: 'Asia/Seoul',                       Name: 'Seoul' },
//   { GmtOffset: '+09:00', Code: 'Asia/Tokyo',                       Name: 'Tokyo' },
//   { GmtOffset: '+09:00', Code: 'Asia/Yakutsk',                     Name: 'Moscow+06 - Yakutsk' },
//   { GmtOffset: '+09:00', Code: 'Pacific/Palau',                    Name: 'Palau' },
//   { GmtOffset: '+10:30', Code: 'Australia/Adelaide',               Name: 'Central Time - Adelaide' },
//   { GmtOffset: '+09:30', Code: 'Australia/Darwin',                 Name: 'Central Time - Darwin' },
//   { GmtOffset: '+10:00', Code: 'Antarctica/DumontDUrville',        Name: 'Dumont D\'Urville' },
//   { GmtOffset: '+10:00', Code: 'Asia/Magadan',                     Name: 'Moscow+07 - Magadan' },
//   { GmtOffset: '+10:00', Code: 'Asia/Vladivostok',                 Name: 'Moscow+07 - Yuzhno-Sakhalinsk' },
//   { GmtOffset: '+10:00', Code: 'Australia/Brisbane',               Name: 'Eastern Time - Brisbane' },
//   { GmtOffset: '+11:00', Code: 'Australia/Hobart',                 Name: 'Eastern Time - Hobart' },
//   { GmtOffset: '+11:00', Code: 'Australia/Sydney',                 Name: 'Eastern Time - Melbourne, Sydney' },
//   { GmtOffset: '+10:00', Code: 'Pacific/Chuuk',                    Name: 'Truk' },
//   { GmtOffset: '+10:00', Code: 'Pacific/Guam',                     Name: 'Guam' },
//   { GmtOffset: '+10:00', Code: 'Pacific/Port_Moresby',             Name: 'Port Moresby' },
//   { GmtOffset: '+11:00', Code: 'Pacific/Efate',                    Name: 'Efate' },
//   { GmtOffset: '+11:00', Code: 'Pacific/Guadalcanal',              Name: 'Guadalcanal' },
//   { GmtOffset: '+11:00', Code: 'Pacific/Kosrae',                   Name: 'Kosrae' },
//   { GmtOffset: '+11:00', Code: 'Pacific/Norfolk',                  Name: 'Norfolk' },
//   { GmtOffset: '+11:00', Code: 'Pacific/Noumea',                   Name: 'Noumea' },
//   { GmtOffset: '+11:00', Code: 'Pacific/Pohnpei',                  Name: 'Ponape' },
//   { GmtOffset: '+12:00', Code: 'Asia/Kamchatka',                   Name: 'Moscow+09 - Petropavlovsk-Kamchatskiy' },
//   { GmtOffset: '+13:00', Code: 'Pacific/Auckland',                 Name: 'Auckland' },
//   { GmtOffset: '+13:00', Code: 'Pacific/Fiji',                     Name: 'Fiji' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Funafuti',                 Name: 'Funafuti' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Kwajalein',                Name: 'Kwajalein' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Majuro',                   Name: 'Majuro' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Nauru',                    Name: 'Nauru' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Tarawa',                   Name: 'Tarawa' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Wake',                     Name: 'Wake' },
//   { GmtOffset: '+12:00', Code: 'Pacific/Wallis',                   Name: 'Wallis' },
//   { GmtOffset: '+14:00', Code: 'Pacific/Apia',                     Name: 'Apia' },
//   { GmtOffset: '+13:00', Code: 'Pacific/Enderbury',                Name: 'Enderbury' },
//   { GmtOffset: '+13:00', Code: 'Pacific/Fakaofo',                  Name: 'Fakaofo' },
//   { GmtOffset: '+13:00', Code: 'Pacific/Tongatapu',                Name: 'Tongatapu' },
//   { GmtOffset: '+14:00', Code: 'Pacific/Kiritimati',               Name: 'Kiritimati' }
// ] as ITimeZone[];


