// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nny53yFxl",
    "aws_user_pools_web_client_id": "4ktdllfdkhua8shk8c6v4iij6v",
    "aws_appsync_graphqlEndpoint": "https://pg2tqb2sbjh5jp43hwu2z4teu4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
