projects:
  ikncu:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src\API.ts
        docsFilePath: src\graphql
        graphQLApiId: 74wkfcu2krbpzd2zuwgpitwsyq
      endpoints:
        prod: >-
          https://wh7aunokg5eupnhfo2c5nj66ai.appsync-api.us-east-1.amazonaws.com/graphql
