projects:
  ikncu:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.ts
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src\graphql\types.ts
        docsFilePath: src\graphql
        graphQLApiId: 74wkfcu2krbpzd2zuwgpitwsyq
