// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cacd3139-0e3b-463c-a98e-68042e62fd18",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6ERiitdKw",
    "aws_user_pools_web_client_id": "76du3rm7jd2bl15m0j3k5mnri2",
    "aws_appsync_graphqlEndpoint": "https://ap2nh6htbjcyzgyu2m4syokcbe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
